name: cleanChat
version: 1.0
main: me.xeya.cleanchat.cleanChat
commands:
   cleanchat:
      description: Clean the chat
      usage: /cleanchat
      aliases: clearchat
      permission: cleanchat.use
      permission-message: No permission!